project:
  type: website
  output-dir: docs

website:
  title: "dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - penguins.qmd
      - icon: house
        href: "smallcoder128.github.io"
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

